### ISSUE TITLE
FRP

### ISSUE THREAD

**Issue by shanyuhai123** [aoxiangsky/blog#1]
你好，我稍微看了下你的项目，frp 配置可能有隐私泄漏问题。

**Comment by aoxiangsky** [comment]
> 你好，我稍微看了下你的项目，frp 配置可能有隐私泄漏问题。

你是哪儿看到我frp配置的呢，我咋搜项目没搜到。。。

**Comment by shanyuhai123** [comment]
之前看是有的，今天再看时没了。

刚看了下你历史 commit 还是有的，本地重新 `git init` 后 `git push -f` 覆盖现在的吧。

**Comment by aoxiangsky** [comment]
> 之前看是有的，今天再看时没了。
> 
> 刚看了下你历史 commit 还是有的，本地重新 `git init` 后 `git push -f` 覆盖现在的吧。

好的
